# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  filter_sets:
    small_size:
      quality: 75
      filters:
        thumbnail:
          size: [600, 350]
          mode: outbound #! decoupe l'image au millieu
    card_size:
      quality: 50
      filters:
        thumbnail:
          size: [300, 150]
          mode: outbound #! decoupe l'image au millieu
    full_size:
      quality: 90
      filters:
        scale:
          dim: [1200, 1000]
